name: "Android - Validate gradle wrapper"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/android-validate-gradle-wrapper.yml
      - '**/gradle-wrapper.jar'

permissions: {}

jobs:
  validate-gradle-wrapper:
    name: Validate gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@16bf8bc8fe830fa669c3c9f914d3eb147c629707 #v4.0.1
