---
name: iOS create screenshots
on:
  push:
    tags:
      - ios/*
  pull_request:
    paths:
      - ios/Gemfile
      - ios/Gemfile.lock
  workflow_dispatch:
jobs:
  test:
    name: Take screenshots
    runs-on: macos-13-xlarge
    env:
      SOURCE_PACKAGES_PATH: .spm
      TEST_ACCOUNT: ${{ secrets.IOS_TEST_ACCOUNT_NUMBER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup go-lang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.14

      - name: Set up yeetd to workaround XCode being slow in CI
        run: |
          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
          sudo installer -pkg yeetd-normal.pkg -target /
          yeetd &
      - name: Configure Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      - name: Configure Xcode project
        run: |
          for file in *.xcconfig.template ; do cp $file ${file//.template/} ; done
          sed -i "" \
            "/HAS_TIME_ACCOUNT_NUMBER =/ s#= .*#= 1234123412341234#" \
            UITests.xcconfig
        working-directory: ios/Configurations

      - name: Bundle
        run: bundle install
        working-directory: ios

      - name: Install protobuf
        run: |
          brew update
          brew install protobuf

      - name: Configure Rust
        # Since the https://github.com/actions/runner-images/releases/tag/macos-13-arm64%2F20240721.1 release
        # Brew does not install tools at the correct location anymore
        # This update broke the rust build script which was assuming the cargo binary was located in ~/.cargo/bin/cargo
        # The workaround is to fix brew paths by running brew bundle dump, and then brew bundle
        # WARNING: This has to be the last brew "upgrade" commands that is ran,
        # otherwise the brew path will be broken again.
        run: |
          brew bundle dump
          brew bundle
          rustup default stable
          rustup update stable
          rustup target add aarch64-apple-ios-sim x86_64-apple-ios

      - name: Create screenshots
        run: bundle exec fastlane snapshot --cloned_source_packages_path "$SOURCE_PACKAGES_PATH"
        working-directory: ios

      - name: Upload screenshot artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-screenshots
          path: ios/Screenshots
